package com.raddan.enums;

public enum Words {
    AFRAID, ANGRY, ARRIVE, BASKET, BELIEVE, BICYCLE, BOTTLE, CAREFUL, CHICKEN,
    CLOTHES, CORRECT, DINNER, ENJOY, FAMILY, FINISH, JAVA, KOTLIN, SUN, ORACLE
}
